### ISSUE TITLE
Error after first run

### ISSUE THREAD

**Issue by macspengo** [eddywashere/node-stripe-membership-saas#13]
Hello,
Having an issue with the software. It works prefectly the first time it is launch. However if I stop and start the software, I get the following error.
##############################################################
#
#   !!! MONGOOSE WARNING !!!
#
#   This is an UNSTABLE release of Mongoose.
#   Unstable releases are available for preview/testing only.
#   DO NOT run this in production.
#
##############################################################

body-parser deprecated bodyParser: use individual json/urlencoded middlewares server/index.js:64:9
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:105:29
connect-mongo deprecated auto_reconnect option is deprecated. Use autoReconnect instead server/index.js:81:10
Express server listening on port 3000
/root/node-stripe-membership-saas/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;
              ^
TypeError: Cannot read property 'length' of undefined
    at processResults (/root/node-stripe-membership-saas/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1581:31)
    at /root/node-stripe-membership-saas/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1619:20
    at /root/node-stripe-membership-saas/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1157:7
    at /root/node-stripe-membership-saas/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1890:9
    at Server.Base._callHandler (/root/node-stripe-membership-saas/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
    at /root/node-stripe-membership-saas/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (/root/node-stripe-membership-saas/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/root/node-stripe-membership-saas/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
    at emit (events.js:107:17)
    at null.<anonymous> (/root/node-stripe-membership-saas/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
    at emit (events.js:110:17)
    at Socket.<anonymous> (/root/node-stripe-membership-saas/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:439:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

Any help you could offer to resolve this issues, would be greatly appreciated. I am running on SmartOS with version 0.12.6 node, mongodb-3.0.3.

**Comment by toadkicker** [comment]
I bumped mongoose to 4.2.5 and seems to be fine.

**Comment by eddywashere** [comment]
closing, feel free to re-open if this still occurs
