### ISSUE TITLE
Server won't start for me

### ISSUE THREAD

**Issue by pixsl** [eddywashere/node-stripe-membership-saas#7]
Definitely something wrong on my end but could you help point out the problem? 

Here's what I see after running node server

127:macrodb sevgevorkyan$ node server
body-parser deprecated bodyParser: use individual json/urlencoded middlewares server/index.js:64:9
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:85:29
connect-mongo deprecated auto_reconnect option is deprecated. Use autoReconnect instead server/index.js:81:10
Express server listening on port 3000
MongoDB Connection Error. Make sure MongoDB is running.

/Users/sevgevorkyan/virtualenvs/macrodb/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/mongo_client.js:409
          throw err
                ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/sevgevorkyan/virtualenvs/macrodb/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/Users/sevgevorkyan/virtualenvs/macrodb/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users/sevgevorkyan/virtualenvs/macrodb/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)

**Comment by anastasia** [comment]
Hopefully you've got it working, but if not, it's mongodb that's the problem.
See this error? "MongoDB Connection Error. Make sure MongoDB is running."
just open up another console window, type the command: ` mongod ` 
and you should be good to go.

**Comment by pixsl** [comment]
Thanks bro I actually got it working later that day. Such a noob mistake -_- kept trying the command in the same terminal window Lol.

Thanks again

**Comment by eddywashere** [comment]
thanks @anastasia!
